### ISSUE TITLE
The "Getting Wood" advancement still requires Tinkers' Construct patterns

### ISSUE THREAD

**Issue by pouchrat** [wendall911/SurvivalistEssentials#1]
["Getting Wood" Advancement](https://github.com/wendall911/SurvivalistEssentials/blob/1.19/src/main/resources/data/survivalistessentials/advancements/getting_wood.json)

**Comment by wendall911** [comment]
Thanks for the report. I'll get a fix out soon.

**Comment by wendall911** [comment]
This and the book fix are in latest release for 1.18.2 and 1.19+ on CurseForge now. Thanks again for the report!
