### ISSUE TITLE
[1.19.2] Better combat prevents knife cutting grass.

### ISSUE THREAD

**Issue by Baggytrousers27** [wendall911/SurvivalistEssentials#3]
Forge 43.1.47
bettercombat-forge-1.4.5+1.19
SurvivalistEssentials-1.19+-4.1.0.0

Better Combat's swingthrugrass option (and potentially exidex's swing through grass) prevents knives from cutting grass.

**Comment by wendall911** [comment]
This is simply a configuration issue with Better Combat. It is designed to not allow breaking grass with weapon-like tools, unless you configure the specific tool.

Here is an example configuration that addresses this in config/bettercombat/fallback_compatibility.json:

Add mod to the blacklist: "blacklist_item_id_regex": "pickaxe|survivalistessentials",

This took me a little reading in the docs to figure out, glad you asked. I'll add to my documentation and provide it in the wiki. There isn't anything I can do from my side to change this in a simple way. As far as I know, this is the only mod that has this issue (with the not breaking grass feature enabled). I love the feature as well, so it doesn't make sense to disable it. Just have the mod ignore this mod for weapons.

Let me know if you need any further assistance with this.

**Comment by wendall911** [comment]
I'm double checking the API to make sure I can't do this automatically.

**Comment by wendall911** [comment]
So there isn't a per-weapon configuration for the swing through grass feature. It is either global, or you have to blacklist the mod to prevent this. Maybe the author will change this in the future.
