### ISSUE TITLE
Carry On changed some code and now it causes a crash

### ISSUE THREAD

**Issue by Kevadroz** [wendall911/SurvivalistEssentials#4]
`java.lang.NoSuchMethodError: 'boolean tschipp.carryon.client.keybinds.CarryOnKeybinds.isKeyPressed(net.minecraft.world.entity.player.Player)'
at survivalistessentials.event.HarvestEventHandler.breakBlock(HarvestEventHandler.java:66)`
Looks like that method is gone.

Survivalist Essentials Version: 1.19+ - 4.1.0.0
CarryOn version: 2.0.5.16
MC 1.19.2

**Comment by wendall911** [comment]
Fix is released on CF.
