### ISSUE TITLE
axe Infinite durability issue

### ISSUE THREAD

**Issue by Arch23-tech** [wendall911/SurvivalistEssentials#8]
Hello Mr. Wendell I noticed whenever  I break a log of a tree using (pandas falling tree) and ( dynamic trees) mod my axe durability just not changing, just Infinitely durable which gives me the feeling of cheating (Lol)....however I have no problem breaking single logs, it works fine but when breaking tree logs things get broken 

Thank you for everything (BTW)

**Comment by wendall911** [comment]
This is a bug with those other mods, but I'll see if I can do something to work around it. The issue is really you fall an entire tree with an axe that has like 5 durability, so it should just break it instantly actually. I'll see what I can do.

**Comment by wendall911** [comment]
Ok, I just tested Dynamic trees 1.19.2 and it is working perfectly. I will continue testing.

**Comment by wendall911** [comment]
Tested 1.19.2 with Pandas Falling Trees and works as expected.

**Comment by Arch23-tech** [comment]
Thank you sir.... maybe I also check my other mods ... I'm using your mods for a long time....maybe there are other mods out there causing this bug... you can close this issue...

Thank you so much for your efforts 🙏

**Comment by wendall911** [comment]
I'm testing on 1.20.1 now to see if it's an issue there. I'll close if I don't find anything.

**Comment by wendall911** [comment]
It is an issue with Pandas in 1.20.1. I'll see what the issue is.

**Comment by wendall911** [comment]
This is a bug in the falling trees mod. https://github.com/PandaDap2006/Pandas-Falling-Trees/issues/83

**Comment by wendall911** [comment]
Ok, and there is a bug in Dynamic Trees as well: https://github.com/DynamicTreesTeam/DynamicTrees/issues/894

There is a workaround, you can install https://www.curseforge.com/minecraft/mc-mods/lmft and the issue is resolved. There was a bug in their tags and this mod works around the issue.
